In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import seaborn as sns

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/al/data/rs22.csv')
dataset = dataset.dropna()
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values



```
# This is formatted as code
```

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[ 1.        0.644052  0.750677 ...  0.       41.       16.      ]
 [ 1.        3.448219  4.111904 ...  0.       45.       16.      ]
 [ 1.        3.009004  3.249393 ...  0.       44.       18.      ]
 ...
 [ 1.        1.324214  1.511553 ...  0.       56.       16.      ]
 [ 1.        2.808302  3.442085 ...  0.       60.        9.      ]
 [ 1.        3.218789  3.623867 ...  0.       53.       19.      ]]


In [ ]:
print(y_train)

[0. 0. 0. ... 1. 1. 0.]


In [ ]:
print(X_test)

[[ 2.          0.40288163  0.26354898 ...  0.         51.
  13.        ]
 [ 2.          0.75287245  0.79777347 ...  0.         51.
  13.        ]
 [ 1.          1.004982    1.426855   ...  0.         49.
  12.        ]
 ...
 [ 1.          0.434224    0.828486   ...  0.         56.
  16.        ]
 [ 2.          1.22098211  1.97511053 ...  0.         60.
  13.        ]
 [ 1.          3.47283878  2.24113265 ...  1.         19.
  12.        ]]


In [ ]:
print(y_test)

[1. 1. 1. ... 1. 1. 1.]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.10078026 -0.17922786 -0.15577338 ... -0.45346625  0.11460566
   0.67161542]
 [-1.10078026  1.09016666  1.30330881 ... -0.45346625  0.40943898
   0.67161542]
 [-1.10078026  0.89134216  0.92889957 ... -0.45346625  0.33573065
   1.55906223]
 ...
 [-1.10078026  0.12866889  0.17451691 ... -0.45346625  1.22023059
   0.67161542]
 [-1.10078026  0.80048807  1.01254565 ... -0.45346625  1.51506391
  -2.4344484 ]
 [-1.10078026  0.98630794  1.09145579 ... -0.45346625  0.99910561
   2.00278563]]


In [ ]:
print(X_test)

[[ 0.16599067 -0.28840123 -0.36723182 ... -0.45346625  0.85168895
  -0.65955479]
 [ 0.16599067 -0.12996686 -0.13532917 ... -0.45346625  0.85168895
  -0.65955479]
 [-1.10078026 -0.01584153  0.13775017 ... -0.45346625  0.70427229
  -1.10327819]
 ...
 [-1.10078026 -0.27421312 -0.1219971  ... -0.45346625  1.22023059
   0.67161542]
 [ 0.16599067  0.08193772  0.37574358 ... -0.45346625  1.51506391
  -0.65955479]
 [-1.10078026  1.10131158  0.49122169 ...  2.20523579 -1.50697756
  -1.10327819]]


## Training the K-NN model on the Training set

1.   List item
2.   List item



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNNclassifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
KNNclassifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_KNNpred = KNNclassifier.predict(X_test)
print(np.concatenate((y_KNNpred.reshape(len(y_KNNpred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_KNNpred)
print(cm)
accuracy_score(y_test, y_KNNpred)*100

[[1902  387]
 [ 306 3157]]


87.95201668984701

# Training the SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
SVMclassifier = SVC(kernel = 'linear', random_state = 0)
SVMclassifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_SVMpred = SVMclassifier.predict(X_test)
print(np.concatenate((y_SVMpred.reshape(len(y_SVMpred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_SVMpred)
print(cm)
accuracy_score(y_test, y_SVMpred)*100

[[1587  702]
 [ 403 3060]]


80.7892906815021

# Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTCclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DTCclassifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_DTCpred = DTCclassifier.predict(X_test)
print(np.concatenate((y_DTCpred.reshape(len(y_DTCpred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_DTCpred)
print(cm)
accuracy_score(y_test, y_DTCpred)*100

[[2286    3]
 [   1 3462]]


99.93045897079277